# Generated by Django 5.2.7 on 2025-11-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_answerlike_questionlike_delete_like_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerlike',
            options={'verbose_name': 'Лайк ответа', 'verbose_name_plural': 'Лайки овтетов'},
        ),
        migrations.AlterModelOptions(
            name='questionlike',
            options={'verbose_name': 'Лайк вопрса', 'verbose_name_plural': 'Лайки вопрсов'},
        ),
    ]
