# Generated by Django 5.2.7 on 2025-11-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_answerlike_options_alter_questionlike_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questiontag',
            unique_together={('question', 'tag')},
        ),
    ]
