# Generated by Django 5.2.7 on 2025-11-23 20:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=core.models.default_avatar, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
