# Generated by Django 5.2.7 on 2025-11-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_avatar_alter_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
