upstream app_server {
    server web:8081;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=100m inactive=60m;

server {
    listen 80;

    client_max_body_size 10M;

    gzip on;
    gzip_types text/plain text/css application/javascript image/jpeg image/png;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /uploads/ {
        alias /app/media/;
        expires 30d;
    }

    # Статика по расширениям
    location ~* \.(js|css|jpeg|jpg|png|gif|ico|html)$ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";

        # Если файла нет в статике, пытаемся отдать через прокси (Django)
        try_files $uri $uri/ @proxy;
    }

    # Вспомогательный блок для try_files
    location @proxy {
        proxy_pass http://app_server;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Проксирование и кэш
    location / {
        proxy_pass http://app_server;
        proxy_set_header Host $host;
        proxy_cache my_cache;
        proxy_cache_valid 200 302 10m;
        add_header X-Proxy-Cache $upstream_cache_status;
    }
}
